---
title: "Missingness"
author: "Richard wang"
date: "2024-11-3"
output: html_document
---
```{r}

library(plm)
library(tidyverse)
library(here)
library(texreg)
library(multgee)
library(table1)
library(dplyr)
library(tidyr)
library(usethis) 
library(countrycode)
library(htmltools)
library(naniar)
library(mice)
```


```{r}
Final_data <- read.csv("data/analytical/finaldata.csv",header=TRUE)
Final_data
```

```{r}
Final_data |>
  arrange(year, ISO) |>
  dplyr::select(-country_name, -ISO, -region, -year) |>
  vis_miss()
```

```{r}
#Log transforming GDP and adding as predictor
Final_data$loggdp <- log(Final_data$gdp1000)

preds_loggdp <- as.formula(" ~ armconf1 + loggdp + OECD + popdens + urban + 
                  agedep + male_edu + temp + rainfall1000 + earthquake + drought")
```


```{r}
matmormod_logGDP <- plm(update.formula(preds_loggdp, matmor ~ .), 
              index = c("ISO", "year"),
              effect = "twoways",
              model = "within",
              data = Final_data)

un5mormod_logGDP <- plm(update.formula(preds_loggdp, un5mor ~ .), 
              index = c("ISO", "year"),
              effect = "twoways",
              model = "within",
              data = Final_data)

infmormod_logGDP <- plm(update.formula(preds_loggdp, infmor ~ .), 
              index = c("ISO", "year"),
              effect = "twoways",
              model = "within",
              data = Final_data)

neomormod_logGDP <- plm(update.formula(preds_loggdp, neomor ~ .), 
              index = c("ISO", "year"),
              effect = "twoways",
              model = "within",
              data = Final_data)
```

```{r}
midata <- Final_data |>
  mutate(ISOnum = as.numeric(as.factor(Final_data$ISO))) |>
  select(-country_name, -ISO)

midata$pctpopdens <- finaldata$popdens / 100
```

```{r}
mice0  <- mice(midata, seed = 100, m = 5, maxit = 0, print = F)
```

```{r}
meth <- mice0$method
meth[c("urban", "male_edu", "temp", "rainfall1000", "matmor", "infmor", "neomor", "un5mor", "loggdp", "pctpopdens")] <- "2l.lmer"
```


```{r}
pred <- mice0$predictorMatrix
pred[c("urban", "male_edu", "temp", "rainfall1000", "matmor", "infmor", "neomor", "un5mor", "loggdp", "pctpopdens"), "ISOnum"] <- -2
```


```{r}
ncol(midata)
length(meth)
```


```{r}
mice.multi.out  <- mice(midata, seed = 100, m = 10, maxit = 20,
                        method = meth,
                        predictorMatrix = pred)
```

```{r}
plot(mice.multi.out)
```